#默认使用配置
spring:
  profiles:
    active: dev
#关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: true
  #上面说了spring-boot 不推荐JSP，想使用JSP需要配置application.properties。
  #添加src/main/resources/application.yml内容：
  #thymeleaf.enabled:false+mvc.view.prefix
  #直接在嵌套的tomcat容器是看不到效果的，因为不支持，例如在IDE直接右键run main函数或者打成可执行的jar包都不行。
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: wht123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5

#配置服务器端口，默认为8080
server:
  port: 8080
#用户回话session过期时间，以秒为单位
  session-timeout: 1000000
  #配置访问路径，默认为/
  #context-path: /index
  #配置Tomcat编码，默认为UTF-8
  tomcat:
    uri-encoding: UTF-8
  #Tomcat是否开启压缩，默认为关闭
  #compression: on

# 自定义属性，可以在Controller中读取
application:
  name: wht
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wht.pay.entity
mapper:
  mappers:  com.wht.pay.dao
  not-empty: false
  identity: MYSQL

